export function address(value){if(!/^0x[0-9a-fA-F]{40}$/.test(value))throw Error('Enter a valid 20-byte address.');return value;}
export function integer(value){const n=Number(value);if(!Number.isSafeInteger(n)||n<0)throw Error('Enter a non-negative safe integer.');return n;}
export function digest(value){if(!/^[0-9a-f]{64}$/.test(value))throw Error('Enter a lowercase 64-character SHA-256 digest.');return value;}
export function commit(value){if(!/^[0-9a-f]{40}$/.test(value))throw Error('Enter a full lowercase 40-character Git commit.');return value;}
export function timestamp(value){const n=Date.parse(value);if(!Number.isFinite(n))throw Error('Complete the expiry date and time.');return Math.floor(n/1000);}
export function succeeded(receipt){const leaders=receipt?.consensus_data?.leader_receipt||[];return receipt?.result_name==='MAJORITY_AGREE'&&leaders.some(x=>x.execution_result==='SUCCESS'&&x.result?.status==='return');}
export function calldata(value){const text=value.trim().toLowerCase();if(!/^0x[0-9a-f]+$/.test(text)||text.length%2!==0||text.length<10)throw Error('Enter valid even-length raw calldata.');return text;}
export function abi(value){let item;try{item=JSON.parse(value)}catch{throw Error('ABI must be valid JSON.')}if(item?.type!=='function'||!/^0x[0-9a-f]{8}$/.test(item.selector)||!Array.isArray(item.inputs)||!item.inputs.length)throw Error('Enter one canonical function ABI with selector and inputs.');const supported=new Set(['address','uint256','bool','bytes32']);if(item.inputs.some(x=>!x.name||!supported.has(x.type)))throw Error('ABI supports address, uint256, bool and bytes32.');return item;}
export function decodeCalldata(abiItem,raw){const text=calldata(raw),body=text.slice(2);if(`0x${body.slice(0,8)}`!==abiItem.selector)throw Error('Raw selector does not match ABI.');if(body.length!==8+64*abiItem.inputs.length)throw Error('Raw calldata length does not match ABI.');return abiItem.inputs.map((input,i)=>{const word=body.slice(8+i*64,72+i*64);let value;if(input.type==='address'){if(!/^0{24}/.test(word))throw Error('Address word is not canonical.');value=`0x${word.slice(24)}`;}else if(input.type==='uint256')value=BigInt(`0x${word}`).toString();else if(input.type==='bool'){const n=BigInt(`0x${word}`);if(n>1n)throw Error('Boolean word is not canonical.');value=n===1n;}else value=`0x${word}`;return{name:input.name,type:input.type,value};});}
